name: Bug Report 02
description: File a bug report.
title: "[🐛Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: 무슨 일이 일어났나요?
      description: 기대했던 동작과 어떤 현상이 보이는지 알려주세요.
      value: |
        - 기대했던 동작:
        - 보이는 현상: 
      render: markdown
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
      render: bash

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
