name: Test Report
description: File a bug report.
title: "[Test]: "
labels: ["bug", "triage"]
assignees:
  - nOctaveLay
body:
  - type: textarea
    attributes:
      label: text area label
      description: text area description
      placeholder: "text area placeholder"
      value: text area value
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Version
      description: What version of our software are you running?
      multiple: false
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](link/to/coc)
          required: true
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
