name: testLabeled
on:
  issues:
    types:
      - opened
      - reopened
    
jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: echo $${{github.event.issue.labels.name}}
        env:
          GH_TOKEN: ${{ secrets.testToken }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
        

