name: addIssue
on:
  issues:
    types:  
      - opened
  # schedule:
  #   - cron: "00 10 * * MON"
    
jobs:          
  add_label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: 
          gh issue create --body "hello!"
        env:
          GH_TOKEN: ${{ secrets.testToken }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: enhancement
