name: Change Paper when incoming PR or PUSH TEST

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # jobs로 들어오는 걸 목적으로 함
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Add paper list to readme.md
      env: 
        CHANGED_FILES: ${{ steps.changed-files.outputs.added_files }}
      run: python ./src/revise_readme.py -d ${CHANGED_FILES}

    # - name: Git Push Action
    #   run: |
    #     git config --global user.name ${{vars.name}}
    #     git config --global user.email ${{vars.email}}
    #     git checkout "임정아"
    #     git add .
    #     git commit -m "change readme.md weekly automatically"
    #     git push
