# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # - run: ls ${{ github.workspace }}
    - run: python generate_readme.py
        # git user email
        # GITHUB_EMAIL: wjddkdml1124@naver.com
        # # git use username
        # GITHUB_USERNAME: nOctaveLay  

        # # https:/<token>@github.com/owner/repo.git
        # PUBLISH_REPO: https:/${{secrets.testToken}}@github.com/nOctaveLay/test.git

