# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

# on:
#   schedule:
#     - cron: "10 * * * *"
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - run: python ../generate_readme.py

    - name: Git Push Action
      uses: x-actions/git-push@v1.0
      with:
        # git user email
        GITHUB_EMAIL: wjddkdml1124@naver.com
        # git use username
        GITHUB_USERNAME: nOctaveLay  
        
        # https:/<token>@github.com/owner/repo.git
        PUBLISH_REPO: https:/${{secrets.testToken}}@github.com/nOctaveLay/test.git
        
        # git branch
        # PUBLISH_BRANCH: # optional
        # # dir to publish
        # PUBLISH_DIR: # optional
              
