name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      # - run: gh issue edit "$NUMBER" --add-assignee ${{github.actor}}
      - run:| 
        gh issue edit "$NUMBER" --add-assignee ${{github.actor}}
        gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.testToken }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: bug
