name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.event.issue.labels}}
  add_assignee:
    runs-on: ubuntu-latest
    if: ${{github.event.issue.labels == ''}}
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --add-assignee ${{github.actor}}
        env:
          GH_TOKEN: ${{ secrets.testToken }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          
  add_label_issues:
    runs-on: ubuntu-latest
    if: ${{github.event.issue.labels == ''}}
    permissions:
      issues: write
    steps:
      - run: 
          gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.testToken }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: bug
